version: '3.8'

services:
  app:
    build: .
    container_name: paas-web
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  redis:
    image: redis:7
    container_name: paas-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
